name: marketplace_app
description: Marketplace poject app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <=3.0.3'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.2.0
  flutter_svg: 2.0.5
  get: ^4.6.5
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1
  flutter_switch: ^0.3.2
  reorderables: ^0.6.0
  charts_flutter: ^0.12.0
  image_picker: ^0.8.7
  path_provider: ^2.0.15
  get_storage: ^2.0.3
  permission_handler: ^9.2.0
  cached_network_image: ^3.2.3
  photo_manager:  ^2.6.0
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  http: ^0.13.4
  hexcolor: ^2.0.6
  dio: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/images/welcome/
    - assets/images/paiements/
    - assets/images/deliver/
    - assets/images/deliver/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: silone
       fonts:
         - asset: assets/fonts/AirbnbCereal_W_Bk.otf
     - family: silone_bold
       fonts:
         - asset: assets/fonts/AirbnbCereal_W_Bd.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
